<a href="https://colab.research.google.com/github/shcho11/00.ML_Practices_2022_KB/blob/main/Xgboost.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive/')

Mounted at /content/drive/


### xgboost
> 머신러닝 알고리즘 대회인 kaggle, KDD cup등에서 우승을 한 팀들이 xgboost를 많이 활용한 것이 알려지면서 주목받음.  
boosting 모델에서 오류를 학습하여 다음 round에 반영시키는 것은 gadient boosting과 큰 차이가 없음.  
다만, 학습을 위한 비용함수에 규제화 식이 추가되어 모델이 과적합 되는 것을 방지함.  
규제화를 통해 복잡한 모델에 패널티를 부여  

$$obj^{(t)} = \sum_1^{n} l(y_i, \hat{y}_i^{(t)}) + \sum_{i=1}^t \Omega(f_i) $$


In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris

In [5]:
# 모델 설치
!pip install xgboost

In [18]:
iris = load_iris()
x = iris.data # X 설명변수
y = iris.target # y 종속변수

In [19]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [20]:
col_nm = iris.feature_names # 설명변수이름
col_nm

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [21]:
# 데이터 분할
from sklearn.model_selection import train_test_split
train_x, test_x, train_y, test_y = train_test_split(x, y, stratify=y)

In [23]:
# 모델 import
!pip install xgboost

In [34]:
from xgboost import plot_importance
from xgboost import XGBClassifier

In [36]:
# 모델 생성

xgbc = XGBClassifier(n_estimators=100, learning_rate=0.1, max_depth=4)
xgbc.fit(train_x, train_y)


'''
xbgoost 주요 파라메터
XGBRegressor(
    max_depth=3, 트리의 최대 깊이
    learning_rate=0.1, 학습률 학습 round별로 가중치를 얼만큼 사용할 것인지 0.01 ~ 0.2 사용
    n_estimators=100, 나무 갯수
    verbosity=1, 
    silent=None, 동작메세지 프린트 여부 0, 1
    objective='reg:linear', 비용함수 reg:squarederror, binary:logistic, multi:softmax
    booster='gbtree', gbtree:트리모델, gblinear:선형모델
    n_jobs=1,
    nthread=None,
    gamma=0,
    min_child_weight=1,
    max_delta_step=0,
    subsample=1,
    colsample_bytree=1,
    colsample_bylevel=1,
    colsample_bynode=1,
    reg_alpha=0,
    reg_lambda=1,
    scale_pos_weight=1,
    base_score=0.5,
    random_state=0,
    seed=None,
    missing=None,
    importance_type='gain',
    **kwargs,
)
'''

"\nxbgoost 주요 파라메터\nXGBRegressor(\n    max_depth=3, 트리의 최대 깊이\n    learning_rate=0.1, 학습률 학습 round별로 가중치를 얼만큼 사용할 것인지 0.01 ~ 0.2 사용\n    n_estimators=100, 나무 갯수\n    verbosity=1, \n    silent=None, 동작메세지 프린트 여부 0, 1\n    objective='reg:linear', 비용함수 reg:squarederror, binary:logistic, multi:softmax\n    booster='gbtree', gbtree:트리모델, gblinear:선형모델\n    n_jobs=1,\n    nthread=None,\n    gamma=0,\n    min_child_weight=1,\n    max_delta_step=0,\n    subsample=1,\n    colsample_bytree=1,\n    colsample_bylevel=1,\n    colsample_bynode=1,\n    reg_alpha=0,\n    reg_lambda=1,\n    scale_pos_weight=1,\n    base_score=0.5,\n    random_state=0,\n    seed=None,\n    missing=None,\n    importance_type='gain',\n    **kwargs,\n)\n"

In [37]:
# 모델 예측
xgbc_pred = xgbc.predict(test_x)

In [39]:
# 평가지표 출력
from sklearn.metrics import confusion_matrix, classification_report
print(confusion_matrix(test_y, xgbc_pred))
print(classification_report(test_y, xgbc_pred))

[[12  0  0]
 [ 0 12  1]
 [ 0  1 12]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       0.92      0.92      0.92        13
           2       0.92      0.92      0.92        13

    accuracy                           0.95        38
   macro avg       0.95      0.95      0.95        38
weighted avg       0.95      0.95      0.95        38

